
package api.lesuser.lesegais.ru;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LesUserFault", targetNamespace = "http://api.lesuser.lesegais.ru/")
public class LesUserFault
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 10000000000L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExecutionMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LesUserFault(String message, ExecutionMessage faultInfo) {
    	super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LesUserFault(String message, ExecutionMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: api.lesuser.lesegais.ru.ExecutionMessage
     */
    public ExecutionMessage getFaultInfo() {
        return faultInfo;
    }

}
