
package api.lesuser.lesegais.ru;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LesUserService", targetNamespace = "http://api.lesuser.lesegais.ru/wsdl", wsdlLocation = "http://testintegration.taskdata.work/portal-api/integration/lesuser/?wsdl")
public class LesUserService
    extends Service
{

    private final static URL LESUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException LESUSERSERVICE_EXCEPTION;
    private final static QName LESUSERSERVICE_QNAME = new QName("http://api.lesuser.lesegais.ru/wsdl", "LesUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://testintegration.taskdata.work/portal-api/integration/lesuser/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LESUSERSERVICE_WSDL_LOCATION = url;
        LESUSERSERVICE_EXCEPTION = e;
    }

    public LesUserService() {
        super(__getWsdlLocation(), LESUSERSERVICE_QNAME);
    }

    public LesUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LESUSERSERVICE_QNAME, features);
    }

    public LesUserService(URL wsdlLocation) {
        super(wsdlLocation, LESUSERSERVICE_QNAME);
    }

    public LesUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LESUSERSERVICE_QNAME, features);
    }

    public LesUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LesUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LesUserServicePortType
     */
    @WebEndpoint(name = "LesUserServicePort")
    public LesUserServicePortType getLesUserServicePort() {
        return super.getPort(new QName("http://api.lesuser.lesegais.ru/wsdl", "LesUserServicePort"), LesUserServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LesUserServicePortType
     */
    @WebEndpoint(name = "LesUserServicePort")
    public LesUserServicePortType getLesUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.lesuser.lesegais.ru/wsdl", "LesUserServicePort"), LesUserServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LESUSERSERVICE_EXCEPTION!= null) {
            throw LESUSERSERVICE_EXCEPTION;
        }
        return LESUSERSERVICE_WSDL_LOCATION;
    }
    

    

}
