
package api.lesuser.lesegais.ru;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LesUserServicePortType", targetNamespace = "http://api.lesuser.lesegais.ru/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LesUserServicePortType {


    /**
     * Получение данных справочника
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetLookupValues
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetLookupValues", action = "egwsdl:GetLookupValues")
    @WebResult(name = "ResponseGetLookupValues", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetLookupValues getLookupValues(
        @WebParam(name = "RequestGetLookupValues", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetLookupValues request)
        throws LesUserFault
    ;

    /**
     * Получение данных справочника Лесопользователей
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetPartyValues
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetPartyValues", action = "egwsdl:GetPartyValues")
    @WebResult(name = "ResponseGetPartyValues", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetPartyValues getPartyValues(
        @WebParam(name = "RequestGetPartyValues", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetPartyValues request)
        throws LesUserFault
    ;

    /**
     * Получение данных Лесопользователя
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetParty
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetParty", action = "egwsdl:GetParty")
    @WebResult(name = "ResponseGetParty", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetParty getParty(
        @WebParam(name = "RequestGetParty", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetParty request)
        throws LesUserFault
    ;

    /**
     * Получение данных справочника
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetContractUnderlyingDocuments
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetContractUnderlyingDocuments", action = "egwsdl:GetContractUnderlyingDocuments")
    @WebResult(name = "ResponseGetContractUnderlyingDocuments", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetContractUnderlyingDocuments getContractUnderlyingDocuments(
        @WebParam(name = "RequestGetContractUnderlyingDocuments", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetContractUnderlyingDocuments request)
        throws LesUserFault
    ;

    /**
     * Получение данных документа
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetDocument
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetDocument", action = "egwsdl:GetDocument")
    @WebResult(name = "ResponseGetDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetDocument getDocument(
        @WebParam(name = "RequestGetDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetDocument request)
        throws LesUserFault
    ;

    /**
     * Добавление документа
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseInsertDocument
     * @throws LesUserFault
     */
    @WebMethod(operationName = "InsertDocument", action = "egwsdl:InsertDocument")
    @WebResult(name = "ResponseInsertDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseInsertDocument insertDocument(
        @WebParam(name = "RequestInsertDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestInsertDocument request)
        throws LesUserFault
    ;

    /**
     * Обновление документа
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseUpdateDocument
     * @throws LesUserFault
     */
    @WebMethod(operationName = "UpdateDocument", action = "egwsdl:UpdateDocument")
    @WebResult(name = "ResponseUpdateDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseUpdateDocument updateDocument(
        @WebParam(name = "RequestUpdateDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestUpdateDocument request)
        throws LesUserFault
    ;

    /**
     * Удаление документа
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseDeleteDocument
     * @throws LesUserFault
     */
    @WebMethod(operationName = "DeleteDocument", action = "egwsdl:DeleteDocument")
    @WebResult(name = "ResponseDeleteDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseDeleteDocument deleteDocument(
        @WebParam(name = "RequestDeleteDocument", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestDeleteDocument request)
        throws LesUserFault
    ;

    /**
     * Получение созданных или измененых документов с указанной даты
     * 
     * @param request
     * @return
     *     returns api.lesuser.lesegais.ru.ResponseGetModifiedDocuments
     * @throws LesUserFault
     */
    @WebMethod(operationName = "GetModifiedDocuments", action = "egwsdl:GetModifiedDocuments")
    @WebResult(name = "ResponseGetModifiedDocuments", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseGetModifiedDocuments getModifiedDocuments(
        @WebParam(name = "RequestGetModifiedDocuments", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "request")
        RequestGetModifiedDocuments request)
        throws LesUserFault
    ;
    
    @WebMethod(operationName = "InsertParty", action = "egwsdl:InsertParty")
    @WebResult(name = "ResponseInsertParty", targetNamespace = "http://api.lesuser.lesegais.ru/", partName = "response")
    public ResponseInsertParty insertParty(
        @WebParam(partName = "request", name = "RequestInsertParty", targetNamespace = "http://api.lesuser.lesegais.ru/")
        RequestInsertParty request
    ) throws LesUserFault;


}
